<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class SavingsTest extends TestCase
{
   use RefreshDatabase;
   use WithFaker;

   public $user;
   public $token;

   public function setUp(): void
   {
       parent::setUp(); // TODO: Change the autogenerated stub

       $this->authenticateUser();

       $this->seed(\DatabaseSeeder::class);
   }


   public function tearDown(): void
   {
       parent::tearDown(); // TODO: Change the autogenerated stub
   }



   public function testUserCanLogSavingsTransactionToWallet()
   {
       $data = [
           "amount" => 5000,
           "locked" => 1,
           "lock_duration" => 2,
           "reference" => uniqid('LOC'),
           "wallet_type" => "savings",
           "mode" => "card"
       ];

       $response = $this->withToken($this->token)
                        ->postJson('api/user/log/savings', $data);

       $response->assertCreated();
   }

   public function testUserCanFetchAllSavings()
   {

   }









    private function authenticateUser()
    {
        $user = factory(User::class)->create();
        $response = $this->postJson('api/auth/login', ["email" => $user->email, "password" => "password"]);
        $data = $response->json();

        $this->token = $data['access_token'];
    }
}
