<?php


namespace App\Repositories;


use App\Interfaces\BaseInterface;

class BankAccountRepository extends BaseRepository
{
    public function create()
    {
        parent::create(); // TODO: Change the autogenerated stub
    }
}
